### ISSUE TITLE
猜干员输入干员名字后报错

### ISSUE THREAD

**Issue by Nenot233** [NumberSir/zhenxun_arktools#13]
03-15 16:54:36 [SUCCESS] nonebot | OneBot V11  | [message.group.normal]: Message  from 2529928842@[群:] "#阿米娅"
03-15 16:54:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
03-15 16:54:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
03-15 16:54:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.nonebot_plugin_bing_chat.common.utils)
03-15 16:54:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.zhenxun_plugin_intercept_withdraw)
03-15 16:54:36 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
03-15 16:54:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)

03-15 16:54:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.parse_bilibili_json)
03-15 16:54:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.zhenxun_arktools.src.game_guess_operator)
03-15 16:54:36 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.nonebot_plugin_bing_chat.common.utils) running complete
03-15 16:54:36 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bilibili_json) running complete
03-15 16:54:36 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete
03-15 16:54:36 [WARNING] zhenxun_arktools | 阿米娅(char_1001_amiya2) => 无 HandbookInfo!
03-15 16:54:36 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.zhenxun_arktools.src.game_guess_operator) running complete
03-15 16:54:36 [ERROR] nonebot | Running Matcher(type='message', module=extensive_plugin.zhenxun_arktools.src.game_guess_operator) failed.
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
 File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_arktools\src\game_guess_operator\__init__.py", line 173, in _
    await handle_arkguess(matcher, event, [cht_name])
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_arktools\src\game_guess_operator\__init__.py", line 111, in handle_arkguess
    await send(image=await game.draw())
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_arktools\src\game_guess_operator\data_source.py", line 96, in draw
    bar = await self.draw_bar(cht)
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_arktools\src\game_guess_operator\data_source.py", line 73, in draw_bar
    race_face = await self.get_race_face(cht)
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_arktools\src\game_guess_operator\data_source.py", line 143, in get_race_face
    return self._correct_face if await cht.get_race() == await self._answer.get_race() else self._wrong_face
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_arktools\src\core\models_v3.py", line 386, in get_race
    return (await self.get_handbook_info()).story_text_audio.race
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_arktools\src\core\models_v3.py", line 378, in get_handbook_info
    return await HandbookInfo().init(id_=data.infoId, data=data.__dict__)
AttributeError: 'NoneType' object has no attribute 'infoId'

**Comment by NumberSir** [comment]
已修复
