### ISSUE TITLE
加载插件报错AttributeError: 'PosixPath' object has no attribute 'rsplit'

### ISSUE THREAD

**Issue by Phantom-Aria** [NumberSir/zhenxun_arktools#14]
克隆仓库重启zhenxun_bot，加载插件的页面有如下报错，不知是什么原因？

04-10 13:33:42 [ERROR] nonebot | Failed to import "zhenxun_arktools"
Traceback (most recent call last):
  File "/home/zhenxun_bot/bot.py", line 17, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/zhenxun_bot/extensive_plugin/zhenxun_arktools/__init__.py", line 142, in <module>
    from .src import *
  File "/home/zhenxun_bot/extensive_plugin/zhenxun_arktools/src/__init__.py", line 14, in <module>
    nonebot.load_plugin(Path(__file__).parent / "game_guess_operator")
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 26, in load_plugin
    manager = PluginManager([module_path])
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 52, in __init__
    self.prepare_plugins()
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 97, in prepare_plugins
    name = _module_name_to_plugin_name(plugin)
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/__init__.py", line 51, in _module_name_to_plugin_name
    return module_name.rsplit(".", 1)[-1]
AttributeError: 'PosixPath' object has no attribute 'rsplit'

**Comment by NumberSir** [comment]
更新一下插件看看还有没有报错

**Comment by Phantom-Aria** [comment]
> 更新一下插件看看还有没有报错

把/usr/local/lib/python3.9/site-packages/nonebot/plugin/init.py 第51行加了一句module_name = str(module_name)解决了，谢谢^_^

**Comment by MobiusT** [comment]
能否告知下nonebot2的版本呢

**Comment by NumberSir** [comment]
> > 更新一下插件看看还有没有报错
> 
> 把/usr/local/lib/python3.9/site-packages/nonebot/plugin/init.py 第51行加了一句module_name = str(module_name)解决了，谢谢^_^

可能是你的 `nonebot2` 版本过低，建议用 `pip install -U nonebot2` 更新至最新版本
