### ISSUE TITLE
【JSON解析错误？】打开gocq后插件报错

### ISSUE THREAD

**Issue by BMC-Gordon0921** [NumberSir/zhenxun_arktools#16]
环境：
设备是MI 8 SE，termux+Ubuntu22.04.2+poetry运行，
Python版本3.10
--------
在运行前下载了最新发行版里的资源文件（data.zip）并正确丢进文件夹。
在真寻启动时一切正常，INFO提示无更新。
连接gocq后，出现如下报错：
![ca1c24e0c9b2ffd45007493b0fec08a](https://user-images.githubusercontent.com/92096046/234491838-d8f652ac-51a8-481f-b6c0-245a2a43fea8.png)
不知道是我本地网络问题还是环境问题，但其他需要JSON解析的似乎也报错而且内容差不多
本小白经过24h排查未发现问题，来此求教

**Comment by BMC-Gordon0921** [comment]
04-26 14:38:19 [INFO] zhenxun_arktools | ===== ARKNIGHTS-SQLITE CONNECTED.
04-26 14:38:20 [INFO] zhenxun_arktools | ##### ARKNIGHTS-SQLITE DATA ALL INITIATING ...
04-26 14:38:20 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled!
Traceback (most recent call last):
  File "/root/zhenxun_bot/bot.py", line 24, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/internal/driver/driver.py", line 146, in _run_hook
    await asyncio.gather(*coros)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/utils.py", line 157, in run_coro_with_catch
    return await coro
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/zhenxun_bot/extra_plugin/zhenxun_arktools/src/utils/database.py", line 431, in _init_db
    await ArknightsDB.init_db()
  File "/root/zhenxun_bot/extra_plugin/zhenxun_arktools/src/utils/database.py", line 54, in init_db
    await ArknightsDB.init_data()
  File "/root/zhenxun_bot/extra_plugin/zhenxun_arktools/src/utils/database.py", line 68, in init_data
    await ArknightsDB._init_building_buff(force)
  File "/root/zhenxun_bot/extra_plugin/zhenxun_arktools/src/utils/database.py", line 92, in _init_building_buff
    data = json.loads(data)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by NumberSir** [comment]
已修复，请更新插件

**Comment by BMC-Gordon0921** [comment]
欸，今天更新完插件之后又去试了一下，这报错怎么一模一样地躺在那里……

**Comment by NumberSir** [comment]
请修改配置文件中的 `GITHUB_RAW` 和  `GITHUB_SITE` 为镜像链接如 `https://ghproxy.com/https://raw.githubusercontent.com` 与 `https://kgithub.com` 然后手动用 `更新方舟素材` 更新

**Comment by BMC-Gordon0921** [comment]
好，遇到新问题：
怀疑自己网络不行以后就换到电信宽带，今天重新跑了一下是这样的：
05-21 14:43:16 [ERROR] nonebot | Running Matcher(type='message', module=extra_plugin.zhenxun_arktools.src.utils) failed.
Traceback (most recent call last):
  File "/root/zhenxun_bot/bot.py", line 25, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/zhenxun_bot/extra_plugin/zhenxun_arktools/src/utils/__init__.py", line 21, in _
    await ArknightsDB.init_data(force=True)
  File "/root/zhenxun_bot/extra_plugin/zhenxun_arktools/src/utils/database.py", line 68, in init_data
    await ArknightsDB._init_building_buff(force)
  File "/root/zhenxun_bot/extra_plugin/zhenxun_arktools/src/utils/database.py", line 87, in _init_building_buff
    if not await ArknightsDB.is_table_empty(BuildingBuffModel) and not force:
  File "/root/zhenxun_bot/extra_plugin/zhenxun_arktools/src/utils/database.py", line 416, in is_table_empty
    count = await model.all().count()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/tortoise/queryset.py", line 1279, in _execute
    _, result = await self._db.execute_query(str(self.query))
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/tortoise/backends/sqlite/client.py", line 34, in translate_exceptions_
    return await func(self, query, *args)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/tortoise/backends/sqlite/client.py", line 141, in execute_query
    rows = await connection.execute_fetchall(query, values)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/aiosqlite/core.py", line 203, in execute_fetchall
    return await self._execute(self._execute_fetchall, sql, parameters)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/aiosqlite/core.py", line 81, in _execute_fetchall
    cursor = self._conn.execute(sql, parameters)
sqlite3.DatabaseError: malformed database schema (ACTIVITY)


在连接gocq后也有一个这样的报错，不知道问题是什么（倒

**Comment by BMC-Gordon0921** [comment]
看起来是数据库问题，但还没找到表的问题在哪

**Comment by BMC-Gordon0921** [comment]
问题解决，是因为网络环境问题导致的数据库不完整，经替换后无报错。
本issue关闭。
