### ISSUE TITLE
Unknown filter param 'name'. Allowed base values are

### ISSUE THREAD

**Issue by Nenot233** [NumberSir/zhenxun_arktools#8]
02-15 08:40:22 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.zhenxun_arktools.src.tool_operator_info)
{'time': , 'self_id': 2, 'post_type': 'message', 'sub_type': 'normal', 'user_id': , 'message_type': 'group', 'message_id': 'message': [{'type': 'text', 'data': {'text': '干员 仇白'}}], 'original_message': [{'type': 'text', 'data': {'text': '干员 仇白'}}], 'raw_message': '干员 仇白', 'font': 0, 'sender': {'user_id': 'nickname': '\u200d', 'sex': 'unknown', 'age': 0, 'card': '', 'area': '', 'level': '', 'role': 'owner', 'title': ''}, 'to_me': False, 'reply': None, 'group_id':, 'anonymous': None, 'message_seq': }
02-15 08:40:22 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.zhenxun_plugin_intercept_withdraw-main) running complete
02-15 08:40:22 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.parse_bilibili_json)
02-15 08:40:22 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bilibili_json) running complete
02-15 08:40:22 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.zhenxun_arktools.src.tool_operator_info) running complete
02-15 08:40:22 [ERROR] nonebot | Running Matcher(type='message', module=extensive_plugin.zhenxun_arktools.src.tool_operator_info) failed.
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
 File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_arktools\src\tool_operator_info\__init__.py", line 29, in _
    cht = await Character.parse_name(name)
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_arktools\src\core\models_v3.py", line 50, in parse_name
    data = await CharacterModel.filter(name=name)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\queryset.py", line 998, in __await__
    self._make_query()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\queryset.py", line 960, in _make_query
    self.resolve_filters(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\queryset.py", line 132, in resolve_filters
    modifier &= node.resolve(model, model._meta.basetable)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\expressions.py", line 359, in resolve
    return self._resolve_kwargs(model, table)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\expressions.py", line 317, in _resolve_kwargs
    key, value = self._get_actual_filter_params(model, raw_key, raw_value)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\expressions.py", line 311, in _get_actual_filter_params
    raise FieldError(f"Unknown filter param '{key}'. Allowed base values are {allowed}")
tortoise.exceptions.FieldError: Unknown filter param 'name'. Allowed base values are ['activityPotentialItemId', 'allSkillLvlup', 'appellation', 'canUseActivityPotentialItem', 'canUseGeneralPotentialItem', 'charId', 'description', 'displayNumber', 'favorKeyFrames', 'groupId', 'id', 'isNotObtainable', 'isSpChar', 'itemDesc', 'itemObtainApproach', 'itemUsage', 'maxPotentialLevel', 'name', 'nationId', 'phases', 'position', 'potentialItemId', 'potentialRanks', 'profession', 'rarity', 'skills', 'subProfessionId', 'tagList', 'talents', 'teamId', 'tokenKey', 'trait']

**Comment by Nenot233** [comment]
素材库手动下载的（因为更新方舟素材和更新方舟数据库指令无任何回复及报错）

**Comment by NumberSir** [comment]
截图看看启动bot时的日志

**Comment by Nenot233** [comment]
02-15 12:56:53 [INFO] zhenxun_arktools | ##### EXTRA FILES DOWNLOAD BEGIN
02-15 12:56:53 [INFO] zhenxun_arktools | ===== EXTRA FILES DOWNLOAD DONE
02-15 12:56:56 [INFO] zhenxun_arktools | ##### ARKNIGHTS-SQLITE CONNECTING ...

02-15 12:56:56 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled!
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\connection.py", line 113, in get
    return storage[conn_alias]
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\connection.py", line 76, in _get_db_info
    return self.db_config[conn_alias]
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\internal\driver\driver.py", line 146, in _run_hook
    await asyncio.gather(*coros)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\utils.py", line 157, in run_coro_with_catch
    return await coro
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_arktools\src\utils\database.py", line 244, in _init_db
    await ArknightsDB.init_db()
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_arktools\src\utils\database.py", line 25, in init_db
    await Tortoise.init(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\__init__.py", line 574, in init
    cls._init_apps(apps_config)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\__init__.py", line 417, in _init_apps
    cls._build_initial_querysets()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\__init__.py", line 440, in _build_initial_querysets
    model._meta.finalise_model()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\models.py", line 308, in finalise_model
    self._generate_filters()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\models.py", line 476, in _generate_filters
    get_overridden_filter_func = self.db.executor_class.get_overridden_filter_func
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\models.py", line 288, in db
    return connections.get(self.default_connection)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\connection.py", line 115, in get
    connection: BaseDBAsyncClient = self._create_connection(conn_alias)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\connection.py", line 90, in _create_connection
    db_info = self._get_db_info(conn_alias)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\connection.py", line 78, in _get_db_info
    raise ConfigurationError(
tortoise.exceptions.ConfigurationError: Unable to get db settings for alias 'default'. Please check if the config dict contains this alias and try again

**Comment by Nenot233** [comment]
02-15 12:56:53 [INFO] zhenxun_arktools | ##### EXTRA FILES DOWNLOAD BEGIN
02-15 12:56:53 [INFO] zhenxun_arktools | ===== EXTRA FILES DOWNLOAD DONE
02-15 12:56:56 [INFO] zhenxun_arktools | ##### ARKNIGHTS-SQLITE CONNECTING ...

02-15 12:56:56 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled!
Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\connection.py", line 113, in get
return storage[conn_alias]
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\connection.py", line 76, in _get_db_info
return self.db_config[conn_alias]
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\BOT\zhenxun_bot\bot.py", line 22, in
nonebot.run()
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot_init_.py", line 273, in run
get_driver().run(*args, **kwargs)
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
uvicorn.run(
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\main.py", line 569, in run
server.run()
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
return asyncio.run(self.serve(sockets=sockets))
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
return loop.run_until_complete(main)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
self.run_forever()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
super().run_forever()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
self._run_once()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
handle._run()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
self._context.run(self._callback, *self._args)

File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\internal\driver\driver.py", line 146, in run_hook
await asyncio.gather(*coros)
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\utils.py", line 157, in run_coro_with_catch
return await coro
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\dependencies_init.py", line 108, in call
return await cast(Callable[..., Awaitable[R]], self.call)(**values)
File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_arktools\src\utils\database.py", line 244, in init_db
await ArknightsDB.init_db()
File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_arktools\src\utils\database.py", line 25, in init_db
await Tortoise.init(
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise_init.py", line 574, in init
cls.init_apps(apps_config)
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise_init.py", line 417, in _init_apps
cls.build_initial_querysets()
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise_init.py", line 440, in _build_initial_querysets
model._meta.finalise_model()
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\models.py", line 308, in finalise_model
self._generate_filters()
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\models.py", line 476, in _generate_filters
get_overridden_filter_func = self.db.executor_class.get_overridden_filter_func
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\models.py", line 288, in db
return connections.get(self.default_connection)
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\connection.py", line 115, in get
connection: BaseDBAsyncClient = self._create_connection(conn_alias)
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\connection.py", line 90, in _create_connection
db_info = self._get_db_info(conn_alias)
File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\connection.py", line 78, in _get_db_info
raise ConfigurationError(
tortoise.exceptions.ConfigurationError: Unable to get db settings for alias 'default'. Please check if the config dict contains this alias and try again

**Comment by Nenot233** [comment]
[2023-02-15.log](https://github.com/NumberSir/zhenxun_arktools/files/10739483/2023-02-15.log)

**Comment by NumberSir** [comment]
你应该装了某个同样用 tortoise-orm 库的插件，比如 aidraw 或 harukabot，数据库初始化冲突了。

试试用 `pip install -U tortoise-orm` 把 tortoise 更新到最新版 0.19.3，如果还是冲突只能修改其他插件的数据库初始化源码或者删掉插件

**Comment by Nenot233** [comment]
已解决
